# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:
let
  static_ips = import ../../modules/static_ips.nix;
  in

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "nvme" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6af54bae-3859-4b81-a81b-90c4d57fee89";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/37B7-CA87";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  networking = {
    useDHCP = lib.mkDefault false;

    networkmanager.enable = false;

    defaultGateway = {
      interface = "eno1";
      address = "192.168.0.55";
    };
    nameservers = [
      "192.168.0.55"
      "1.1.1.1"
      "8.8.8.8"
      "9.9.9.9"
    ];
    
    interfaces = {
      eno1 = {
        name = "eno1";
        useDHCP = false;
        ipv4 = {
          addresses = [
            {
              address = static_ips.elitedesk_ip;
              prefixLength = 24;
            }
          ];
        };
      };
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
