_: let
  const = import ../global_constants.nix;
in {
  # Bootloader.
  boot = {
    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;
    initrd.systemd.enable = true;
  };

  nixpkgs.config.allowUnfree = true;

  security = {
    polkit.enable = true;
    # Root CA for in-cluster services (*.k3s.lan), generated by cert-manager.
    # See env/cert_manager.nix. Public certificate only; the key stays in the cluster.
    pki.certificateFiles = [./k3s-lan-ca.crt];
    pam.loginLimits = [
      {
        domain = "*";
        type = "soft";
        item = "nofile";
        value = "65536";
      }
    ];
  };

  services = {
    openssh.enable = true;
    tailscale.enable = true;
  };

  # Hostnames for services behind the k3s traefik ingress, reachable over
  # tailscale. Any cluster node works; this is de-msa2's tailscale IP.
  networking.hosts."100.83.142.17" = [
    "home.k3s.lan"
    "argocd.k3s.lan"
    "iggy.k3s.lan"
    "greptimedb.k3s.lan"
    "clickhouse.k3s.lan"
    "tikr.k3s.lan"
    "tikr-dev.k3s.lan"
    "ntfy.k3s.lan"
    "forgejo.k3s.lan"
    "grafana.k3s.lan"
    "vikunja.k3s.lan"
    "bencher.k3s.lan"
    "bencher-api.k3s.lan"
    "llama.k3s.lan"
  ];

  nix.settings = {
    experimental-features = ["nix-command" "flakes"];
    trusted-users = ["root" "${const.username}"];
    download-buffer-size = 500000000; # 500 MiB
  };

  system.switch = {
    enable = true;
  };

  hardware.keyboard.qmk.enable = true;

  programs = {
    dconf.enable = true;
    gnupg.agent = {
      enable = true;
      enableSSHSupport = true;
    };
    nix-ld = {
      enable = true;
      libraries = [];
    };
  };

  # Don't ask for user password for main user.
  security.sudo.extraRules = [
    {
      users = ["${const.username}"];
      commands = [
        {
          command = "ALL";
          options = ["NOPASSWD"];
        }
      ];
    }
  ];
}
