# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: let
  static_ips = import ../../modules/static_ips.nix;
  main_nic = "enp3s0";
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "ahci" "xhci_pci" "thunderbolt" "usbhid" "uas" "sd_mod"];
      kernelModules = [];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/24638f70-8606-4acb-9905-0058a6fffcc9";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/7514-EBBB";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking = {
    # hostId can be generated with `head -c4 /dev/urandom | od -A none -t x4`
    hostId = "6bfb96a2";

    useDHCP = lib.mkDefault false;
    networkmanager.enable = false;

    defaultGateway = {
      interface = main_nic;
      address = "192.168.0.55";
    };
    nameservers = [
      "1.1.1.1"
      "8.8.8.8"
      "9.9.9.9"
    ];
    interfaces = {
      "${main_nic}" = {
        useDHCP = false;
        ipv4 = {
          addresses = [
            {
              address = static_ips.de-n5_ip;
              prefixLength = 24;
            }
          ];
        };
        wakeOnLan.enable = true;
      };
    };
  };
}
