apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: k3s-lan-ca
    gethomepage.dev/description: Dashboards
    gethomepage.dev/enabled: "true"
    gethomepage.dev/external: "true"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: grafana.svg
    gethomepage.dev/name: grafana
    gethomepage.dev/siteMonitor: http://grafana.grafana.svc.cluster.local
  name: grafana
  namespace: grafana
spec:
  ingressClassName: traefik
  rules:
    - host: grafana.k3s.lan
      http:
        paths:
          - backend:
              service:
                name: grafana
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - grafana.k3s.lan
      secretName: grafana-tls
