apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: k3s-lan-ca
    gethomepage.dev/description: GitOps continuous delivery
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: DevOps
    gethomepage.dev/icon: argo-cd.svg
    gethomepage.dev/name: ArgoCD
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.4.3
    helm.sh/chart: argo-cd-9.5.20
  name: argocd-server
  namespace: argocd
spec:
  ingressClassName: traefik
  rules:
    - host: argocd.k3s.lan
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - argocd.k3s.lan
      secretName: argocd-server-tls
