# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: let
  static_ips = import ../../modules/static_ips.nix;
  const = import ./constants.nix;
  # main_nic = "ens5f0";
  main_nic = "eno1";
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["megaraid_sas" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
      kernelModules = [];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  # NVME disk
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/aa996a56-374d-4cee-aacf-14f4f44ff014";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/8E8C-F51F";
      fsType = "vfat";
    };
  };

  swapDevices = [];

  networking = {
    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    useDHCP = lib.mkDefault false;

    networkmanager.enable = true;

    defaultGateway = {
      interface = main_nic;
      address = "192.168.0.55";
    };
    nameservers = [
      "192.168.0.55"
      "1.1.1.1"
      "8.8.8.8"
      "9.9.9.9"
    ];

    interfaces = {
      "${main_nic}" = {
        name = "${main_nic}";
        useDHCP = false;
        mtu = 9000;
        ipv4 = {
          addresses = [
            {
              address = static_ips.poweredge_ip;
              prefixLength = 24;
            }
          ];
        };
        # Can also manually set using `sudo ethtool -s enp3s0 wol g`
        wakeOnLan.enable = true;
        # Primarily set here to know where to send wakeOnLan packet using `wakeonlan $macAddress`
        macAddress = "70:b5:e8:d0:ac:24";
      };
    };
    firewall.allowedTCPPorts = [
      const.iperf_port # iperf server
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
