# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: let
  static_ips = import ../../modules/static_ips.nix;
  main_nic = "eno1";
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3abe28a7-bae2-44f0-bf15-07273a9c3431";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C7D4-4A0B";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  networking = {
    useDHCP = lib.mkDefault true;
    networkmanager.enable = true;

    defaultGateway = {
      interface = main_nic;
      address = "192.168.0.55";
    };
    nameservers = [
      "${static_ips.elitedesk_ip}"
    ];
    interfaces = {
      "${main_nic}" = {
        useDHCP = false;
        ipv4 = {
          addresses = [
            {
              address = static_ips.superserver_ip;
              prefixLength = 24;
            }
          ];
        };
        # Can also manually set using `sudo ethtool -s eno1 wol g`
        wakeOnLan.enable = true;
        # Primarily set here to know where to send wakeOnLan packet using `wakeonlan $macAddress`
        macAddress = "ac:1f:6b:e5:87:d4";
      };
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
