# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: let
  static_ips = import ../../modules/static_ips.nix;
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/2464e526-28d4-43d3-b885-c3284a8a0d04";
      fsType = "xfs";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/9F46-467D";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  swapDevices = [];

  networking = {
    useDHCP = lib.mkDefault true;
    networkmanager.enable = true;

    defaultGateway = {
      interface = "enp65s0f0";
      address = "192.168.0.55";
    };
    nameservers = [
      "${static_ips.elitedesk_ip}"
    ];

    interfaces.enp65s0f0 = {
      name = "enp65s0f0";
      useDHCP = false;
      mtu = 9000;
      ipv4 = {
        addresses = [
          {
            address = "${static_ips.superserver_ip}";
            prefixLength = 24;
          }
        ];
      };
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
