apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ax-controller
    app.kubernetes.io/part-of: ax
  name: ax-controller
  namespace: ax-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ax-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ax-controller
    spec:
      containers:
        - args:
            - --redis-addr=ax-redis.ax-system.svc.cluster.local:6379
            - --substrate-endpoint=api.ate-system.svc.cluster.local:443
            - --substrate-authority=api.ate-system.svc
            - --substrate-token-file=/var/run/secrets/ateapi/token
            - --substrate-ca-file=/run/servicedns-ca/trust-bundle.pem
            - --template=default-template
            - --template-atespace=ax-system
          env:
            - name: ATENET_ROUTER_ADDR
              value: atenet-router.ate-system.svc.cluster.local:80
            - name: AX_SNAPSHOTS_BUCKET
              value: gs://ate-snapshots/ax/
            - name: AX_DEFAULT_TASK_IMAGE
              value: forgejo.k3s.lan/mathiswellmann/ax-task-runner@sha256:3ffa731ddf76e8d917493a1a01710e6596b131c3192b2b917cbe6134a678ebf8
          image: de-msa2:2999/mathiswellmann/ax-controller:d8ed0fe38bce@sha256:048cce3548d0ad174892a87aa66c5b0f2f128d185e87bb6c2d88f15dd5dfc31c
          name: controller
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/run/secrets/ateapi
              name: ate-token
              readOnly: true
            - mountPath: /run/servicedns-ca
              name: servicedns-ca
              readOnly: true
      serviceAccountName: ax-controller
      volumes:
        - name: ate-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: api.ate-system.svc
                  expirationSeconds: 7200
                  path: token
        - name: servicedns-ca
          projected:
            defaultMode: 420
            sources:
              - clusterTrustBundle:
                  labelSelector:
                    matchLabels:
                      podcert.ate.dev/canarying: live
                  path: trust-bundle.pem
                  signerName: servicedns.podcert.ate.dev/identity
