apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podcert-ate-dev-signer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podcert-ate-dev-signer
subjects:
  - kind: ServiceAccount
    name: default
    namespace: podcertificate-controller-system
