apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ate-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ate-controller
subjects:
  - kind: ServiceAccount
    name: ate-controller
    namespace: ate-system
