apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atelet
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ate.dev
    resources:
      - csidriverconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ate.dev
    resources:
      - sandboxconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - clustertrustbundles
    verbs:
      - get
      - watch
      - list
