apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ate-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ate.dev
    resources:
      - workerpools
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ate.dev
    resources:
      - workerpools/finalizers
    verbs:
      - update
  - apiGroups:
      - ate.dev
    resources:
      - workerpools/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - certificates.k8s.io
    resources:
      - clustertrustbundles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - certificates.k8s.io
    resourceNames:
      - egress-mitm.ate.dev/*
    resources:
      - signers
    verbs:
      - attest
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
