apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podcertificate-controller
  name: podcertificate-controller
  namespace: podcertificate-controller-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podcertificate-controller
  template:
    metadata:
      labels:
        app: podcertificate-controller
    spec:
      containers:
        - args:
            - --in-cluster=true
            - --sharding-pod-namespace=$(POD_NAMESPACE)
            - --sharding-pod-name=$(POD_NAME)
            - --sharding-pod-uid=$(POD_UID)
            - --sharding-application-name=podcertificate-controller
            - --service-dns-ca-pool=/run/ca-state/service-dns-pool.json
            - --pod-identity-ca-pool=/run/ca-state/pod-identity-pool.json
            - --workers-per-signer=$(WORKERS_PER_SIGNER)
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: WORKERS_PER_SIGNER
              value: "1"
          image: de-msa2:2999/mathiswellmann/podcertcontroller:dc1f263076d1@sha256:ff9ce1ab7fcf0f80761469340e9e89b2c2f5de7539ca8eaea5269e97f4f57df6
          name: controller
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /run/ca-state
              name: ca-state
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: ca-state
          projected:
            sources:
              - secret:
                  items:
                    - key: pool
                      path: service-dns-pool.json
                  name: service-dns-ca-pool
              - secret:
                  items:
                    - key: pool
                      path: pod-identity-pool.json
                  name: pod-identity-ca-pool
