apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ate-controller
  namespace: ate-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ate-controller
subjects:
  - kind: ServiceAccount
    name: ate-controller
    namespace: ate-system
