apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: atelet-endpointslices
  namespace: ate-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: atelet-endpointslices
subjects:
  - kind: ServiceAccount
    name: atelet
    namespace: ate-system
