apiVersion: v1
kind: Secret
metadata:
  name: ate-api-server-secret-envvars
  namespace: ate-system
stringData:
  ATE_API_POSTGRES_CONNECTION_STRING: postgresql://postgres@postgres.ate-system.svc:5432/atepg?sslmode=verify-full&sslrootcert=/run/servicedns.podcert.ate.dev/trust-bundle.pem&sslcert=/run/podidentity.podcert.ate.dev/credential-bundle.pem&sslkey=/run/podidentity.podcert.ate.dev/credential-bundle.pem
  ATE_API_POSTGRES_SCHEMA: public
type: Opaque
