apiVersion: v1
kind: Service
metadata:
  name: atenet-router
  namespace: ate-system
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: connect
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: connect-tls
      port: 8444
      protocol: TCP
      targetPort: 8444
    - name: status
      port: 4040
      protocol: TCP
      targetPort: status
  selector:
    app: atenet-router
  type: ClusterIP
