apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ate-system
spec:
  clusterIP: None
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: grpc
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: ate-api-server
