apiVersion: ate.dev/v1alpha1
kind: WorkerPool
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    workload: gvisor
  name: gvisor
  namespace: ate-system
spec:
  replicas: 3
  sandboxClass: gvisor
  template:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - de-msa2
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 4Gi
  workerImage: de-msa2:2999/mathiswellmann/ateom-gvisor:dc1f263076d1@sha256:cb2b58f1a2c663b15e9cfcc8ac8f0a3f8b16f782f20cfe5a9dbf441b759f9dcd
