apiVersion: ate.dev/v1alpha1
kind: WorkerPool
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    workload: gvisor
  name: gvisor
  namespace: ate-system
spec:
  replicas: 3
  sandboxClass: gvisor
  template:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - de-msa2
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 4Gi
  workerImage: de-msa2:2999/mathiswellmann/ateom-gvisor:dc1f263076d1@sha256:c5fae3d5f44b972fe0d469005e6304f1037a142dfa58ff9b6aafc4b0c1bc79ab
