apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubernetes.io/service-account.name: meshify-admin
  name: meshify-admin-token
  namespace: kube-system
type: kubernetes.io/service-account-token
