# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: let
  static_ips = import ../../modules/static_ips.nix;
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/39a24096-bef9-4bc1-8c36-f44383cc337d";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/240d462d-19e8-472b-86bf-654cd379c683";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4A0C-90FB";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  networking = {
    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    useDHCP = lib.mkDefault false;

    networkmanager.enable = false;

    defaultGateway = {
      interface = "enp4s0";
      address = "192.168.0.55";
    };
    nameservers = [
      "192.168.0.55"
      "1.1.1.1"
      "8.8.8.8"
      "9.9.9.9"
    ];

    interfaces = {
      eno1 = {
        name = "enp4s0";
        useDHCP = false;
        ipv4 = {
          addresses = [
            {
              address = static_ips.genoa_ip;
              prefixLength = 24;
            }
          ];
        };
      };
      # Mellanox ConnectX-3-Pro 40G
      # enp7s0 = {
      #   name = "enp7s0";
      #   useDHCP = false;
      #   mtu = 9000;
      #   ipv4 = {
      #     addresses = [
      #       {
      #         address = static_ips.de-rosen_mellanox_0;
      #         prefixLength = 16;
      #       }
      #     ];
      #   };
      # };
      enp7s0d1 = {
        name = "enp7s0d1";
        useDHCP = false;
        mtu = 9000;
        ipv4 = {
          addresses = [
            {
              address = static_ips.de-rosen_mellanox_1;
              prefixLength = 28;
            }
          ];
        };
      };
    };
    firewall.allowedTCPPorts = [
      5201 # iperf server
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
