apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: attic
  namespace: argocd
spec:
  destination:
    namespace: attic
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/prod/attic
    repoURL: https://github.com/MathisWellmann/nixos-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
