apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  name: substrate
  namespace: argocd
spec:
  destination:
    namespace: ate-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/prod/substrate
    repoURL: https://github.com/MathisWellmann/nixos-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
