# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  pkgs,
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usbhid" "uas" "sd_mod"];
      kernelModules = [];
    };
    kernelModules = ["kvm-intel"];
    kernelParams = ["nvidia-drm.modeset=1" "nvidia-drm.fbdev=1" "nvidia.NVreg_OpenRmEnableUnsupportedGpus=1"];
    extraModulePackages = [];
    extraModprobeConfig = ''
      options nvidia NVreg_RestrictProfilingToAdminUsers=0
    '';
    kernelPackages = pkgs.linuxPackages_latest;
    # Nouveau is blacklisted because we use the proprietary NVIDIA driver.
    # i915/xe must stay loaded — the laptop eDP panel is physically wired
    # through the Intel iGPU even when NVIDIA PRIME sync renders everything.
    blacklistedKernelModules = ["nouveau"];
  };
  hardware.nvidia.prime = {
    sync.enable = true;
    # Verify with: lspci | grep -E 'VGA|3D'
    intelBusId = "PCI:0:2:0";
    nvidiaBusId = "PCI:1:0:0";
  };
  # /dev/dri/cardN numbering is NOT stable on this machine: the boot
  # simple-framebuffer device plus the i915/nvidia probe order shuffle it
  # (NVIDIA has been observed as card0, card1 and card2 on different boots),
  # so hardcoded cardN paths randomly point Hyprland at the wrong device.
  # The /dev/dri/by-path/* names cannot be used either, because aquamarine
  # splits AQ_DRM_DEVICES on ':' and the PCI by-path names contain colons.
  # Therefore create stable, colon-free symlinks via udev and use those.
  services.udev.extraRules = ''
    SUBSYSTEM=="drm", KERNEL=="card[0-9]*", DRIVERS=="nvidia", SYMLINK+="dri/nvidia-card"
    SUBSYSTEM=="drm", KERNEL=="card[0-9]*", DRIVERS=="i915", SYMLINK+="dri/igpu-card"
  '';
  environment.sessionVariables = {
    # NVIDIA dGPU first (primary renderer, matches GBM_BACKEND=nvidia-drm),
    # Intel iGPU second so aquamarine can scan out on the eDP panel.
    AQ_DRM_DEVICES = "/dev/dri/nvidia-card:/dev/dri/igpu-card";
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/f9da323d-3d71-403a-be88-bb831da87b2c";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/1973-9011";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp45s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
